### ISSUE TITLE
php-fpm autostart with osx-php

### ISSUE THREAD

**Issue by pjezek** [liip/php-osx#145]
Hi there,
I created a plist file intendet do autostart php-fpm on OSX. _Would this be interesting to share?_

File: _etc/php-fpm.plist_

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <false/>
    <key>Label</key>
    <string>ch.liip.php-osx.php-fpm</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/php5/sbin/php-fpm</string>
      <string>-c /usr/local/php5/lib/php.ini</string>
      <string>-D</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>/usr/local/php5/var/run</string>
    <key>StandardOutPath</key>
    <string>/usr/local/php5/var/log/php-fpm.log</string>
    <key>StandardErrorPath</key>
    <string>/usr/local/php5/var/log/php-fpm.log</string>
  </dict>
</plist>
```

It can be activated by:

```
ln -s /usr/local/php5/etc/php-fpm.plist ~/Library/LaunchAgents/
```

And started manually with these intstructions:

```
launchctl load ~/Library/LaunchAgents/php-fpm.plist
```

**Comment by philrennie** [comment]
Handy. For anyone else finding this through a google search as I did I'd suggest changing it to not daemonize, otherwise it can't be stopped with launchctl.
Unser <key>ProgramArguments</key> change
<string>-D</string>
to 
<string>-F</string>

Also worth noting that you need to rename/duplicate the following files to remove .default
/usr/local/php5/etc/php-fpm.conf.default
/usr/local/php5/etc/php-fpm.d/www.conf.default

**Comment by cfmDeveloper** [comment]
I notice this still isn't in the latest release.  Any feedback as to why or if there are plans to add it?  I was having a hard time figuring out how to get php-fpm to work with the install so i can use nginx without installing the brew version of php that doesn't have the extensions included that this project does.
