### ISSUE TITLE
Extension request: yaml

### ISSUE THREAD

**Issue by vgoebbels** [liip/php-osx#15]
Hi, it would be very helpful to have a yaml extension. Thanks for your work.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
