### ISSUE TITLE
new install; 99-liip-developer.ini empty

### ISSUE THREAD

**Issue by markmanley** [liip/php-osx#152]
Hi; just installed the latest stable release(5.6) and noted that the 99-liip-developer.ini file exists, but is empty. No error messages on install. Any ideas why? Thanks in advance!

**Comment by aidanamavi** [comment]
I'm new to the project, but I presume it was created for developers to run their own custom php configurations in one place.

This saves the developer from having to edit and get lost in other configuration files. The word 'liip' is used because that is the name of the organization leading the development of this project.

You can delete the 99-liip-developer.ini file, if you wish, without any consequences. You can also add your own such as 99-markmanley-developer.ini, which you could then add a php configuration for your time zone, such as:
```
date.timezone = "America/New_York"
```
The number signifies the order in which configurations are run, so 99 will run last and any configurations made in that config will override any of the others run before it.

**Comment by beatjunky99** [comment]
Same with latest 5.5 install. :disappointed: 
Really liked your provided defaults in 99-liip-developer.ini.

**Comment by ikwattro** [comment]
Same for me, however adding `date.timezone` does not seems to take effect :(

**Comment by nasht00** [comment]
Same here.
Like @aidanamavi said, I suspect it's by design to put just your own custom modifications.
However if that's the case, the website needs to be updated.
It clearly lead me to believe that some default values exist in this file:

Some quotes:

"Change the file in /usr/local/php5/php.d/99-liip-developer.ini to adjust that."

"We introduced our own ini file to be able to easily overwrite the standard values with **our recommended values**. You can find it in /usr/local/php5/php.d/99-liip-developer.ini"

"You can change that value in /usr/local/php5/php.d/99-liip-developer.ini"

**Comment by javiereguiluz** [comment]
Same here. After upgrading to 5.6.14, all applications fail because `99-liip-developer.ini` is empty and thus, the `date.timezone` option is not set.

**Comment by chregu** [comment]
Fixed this, it comes now included again with this file
