### ISSUE TITLE
Did or could not download package: 5.6-10.10-frontenddev

### ISSUE THREAD

**Issue by behzadsh** [liip/php-osx#173]
Every time I try to install php 5.6 I get this message

```
downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tar.bz2
downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tar.gz
downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tgz
Did or could not download package: 5.6-10.10-frontenddev
```

It also happens with other versions

**Comment by chregu** [comment]
Works fine for me.
````
$ curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
****
[WARNING]
Detected OS X El Capitan 10.11. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time)
downloading http://php-osx.liip.ch/install/5.6-10.10-frontenddev-latest.dat
downloading http://php-osx.liip.ch/install/5.6-10.10/frontenddev/5.6-10.10-frontenddev-5.6.17-20160108-105408.tar.bz2
```

do you have some more info?

**Comment by behzadsh** [comment]
@chregu unfortunately no, I get the message I wrote after `downloading http://php-osx.liip.ch/install/5.6-10.10/frontenddev/5.6-10.10-frontenddev-5.6.17-20160108-105408.tar.bz2`

seems like `5.6-10.10-frontenddev` file not downloaded correctly

**Comment by arnoldsmyth** [comment]
I have this same issue with php7. I had found the instructions with 5.6 so replaced it with 7 and 7.0.3 - in both cases I got this error.

I went to http://php-osx.liip.ch/ and noticed in the Intro that there were specific version numbers listed. When I tried 7.0 it worked. It seems that it is an issue with the version number used.

**Comment by robrothedev** [comment]
I am also getting the 'Did or could not download package: 5.6-10.10-frontenddev' error message.  Example:

curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
****
[WARNING]
Detected OS X El Capitan 10.11. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Password:
Start packager (may take some time)
downloading http://php-osx.liip.ch/install/5.6-10.10-frontenddev-latest.dat
downloading http://php-osx.liip.ch/install/5.6-10.10/frontenddev/5.6-10.10-frontenddev-5.6.21-20160524-232350.tar.bz2

downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tar.bz2
downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tar.gz
downloading http://php-osx.liip.ch/5.6-10.10-frontenddev.tgz
Did or could not download package: 5.6-10.10-frontenddev

Any ideas on why this might happen?

**Comment by kemenydev** [comment]
Try the command below. It worked for me.

curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6

**Comment by matthewxu** [comment]
I also get the error

****
Proceeding
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10/frontenddev/7.1-10.10-frontenddev-7.1.21-20180903-114446.tar.bz2

downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.1-10.10-frontenddev.tar.bz2
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.1-10.10-frontenddev.tar.gz
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.1-10.10-frontenddev.tgz
Did or could not download package: 7.1-10.10-frontenddev
Finished.

**Comment by nebbian** [comment]
I'm getting the same error as well.  

`$ curl -s https://php-osx.liip.ch/install.sh | bash -s force 5.4
****
[WARNING]
Detected macOS Mojave 10.14. There are serious issues with it, due to the original apache not loading
foreign libraries anymore. PHP within apache will most certainly not work anymore if you proceed!
The cli version still will.
See this issue at https://github.com/liip/php-osx/issues/249 for details and discussion
****
Proceeding
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/5.4-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/<?xml version="1.0" encoding="UTF-8"?>

downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.4-10.10-frontenddev.tar.bz2
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.4-10.10-frontenddev.tar.gz
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.4-10.10-frontenddev.tgz
Did or could not download package: 5.4-10.10-frontenddev
Finished.`
