### ISSUE TITLE
OpenSSL and cURL update?

### ISSUE THREAD

**Issue by mo3chin3** [liip/php-osx#175]
Hey guys, first off thank you for you work on this project it has helped me a ton!  I am using Paypal's IPN and PDT for a payment confirmation and recently they updated the backend tls configuration and now those do not work.  It looks like the OpenSSL and cURL are too old to continue to work with it.  Is there any chance you can update those in the 5.6 release?  Or provide some instruction on how to update those in the php install?  I've been trying for a couple of weeks without success so I'm hoping your expertise can help out.

**Comment by mjmartin** [comment]
Yeh, agreed, TLS1.0 is going the way of the dodo, need openssl 1.0.1+ really

**Comment by fullybaked** [comment]
We've just hit this one hard too.  One of our API vendors has gone TLS 1.2 only for _reasons_ and we can't hit the endpoint from any dev box using Liip package.  Ditto the thanks for this great package, but really need TLS 1.2 to continue using it.

**Comment by chregu** [comment]
We build against the openssl libraries coming with OS X. Aren't those supporting TLS 1.2 only sites? 
Anyway, updating libcurl now, at least

**Comment by chregu** [comment]
Updated to latest curl. Can you please test

**Comment by fullybaked** [comment]
Nope, still no working.

**Comment by chregu** [comment]
Do you have an example URL/code, where it doesn't work?

**Comment by fullybaked** [comment]
This was sent over by our API vendor and returns output of TLS 1.0 on all machines using the Liip package
```
<?php

$ch = curl_init('https://www.howsmyssl.com/a/check');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$data = curl_exec($ch);

curl_close($ch);

 

$json = json_decode($data);

echo $json->tls_version . PHP_EOL;

$curl_info = curl_version();

echo $curl_info['ssl_version'];

?>
```

Also using the latest CakePHP 3.x built in Http client to send requests throws "Failed crypto" exceptions on any request to a TLS 1.2 only endpoint

**Comment by fullybaked** [comment]
Just as one other piece of info (helpful or not) I just installed PHP56 from Homebrew and this dones't have the same issues.  

Output from the above script is 

```
TLS 1.2
SecureTransfer
```

and the CakePHP client works.

**Comment by chregu** [comment]
Yes, realized that now too. Let's see how I can compile curl against SecureTransport instead of openssl.

**Comment by chregu** [comment]
Ok, done. Can you please try again. It seems to work on my side now

**Comment by fullybaked** [comment]
Ok, the test script from the vendor now has TLS 1.2 as output but it seems that TLS 1.2 is still not registered as a stream socket transport

`php -i | grep ssl` 

Liip 
```
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0
```

Homebrew
```
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
```

This means that while the basics are working, there still seems to be an issue when using fopen with stream contexts.

**Comment by chregu** [comment]
argh, you're example was using curl, not fopen, so i didn't check that before I compiled everything new again.. But it looks like that definitely needs an updated openssl library, not sure when I want to dig into that rabbithole

**Comment by fullybaked** [comment]
Damn.  Sorry.  I should have been more clear on the framework side of the original post, :/ 

Ok.  Thanks for your time today.

**Comment by lphilps** [comment]
I too have benefited greatly from the PHP 5.6 version of this package. So, first off, many thanks to the creators/maintainers!

This issue is now impacting me too as a new third party web service I need to use is also insisting on TLS v1.2. So, I spent a bit of time poking around and found:

- The openssl version included with El Capitan‎ is OpenSSL 0.9.8zg, which is not what we all want/need.  If you run openssl ciphers, you won't see anything terribly modern. :-(
- I installed the latest version of openssl via homebrew,  v1.0.2f, and the openssl ciphers output it produces does list all the protocols we want.
- I used the test php script provided above by @fullybaked and ran it with Apple's El Capitan‎ PHP v5.5 and it came up with TLS 1.2: SecureTransport - it seems to support the right transports.
- So, I ran "/usr/bin/php -i" as well to look at the compile line for that version of PHP to see how Apple configured/built it and found it included this directive: --with-openssl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/local

Now the directory MacOSX10.11.Internal.sdk doesn't appear to ship with XCode :-/, but it's interesting that you can specify the openssl directory in the --with-openssl parameter. :-)

So ... hypothetically, if we installed the current version of openssl from (for example) homebrew  (1.0.2f)  and then built php using:

--with-openssl=/usr/local/opt/openssl/lib

... maybe that would do it? I don't have time to attempt a build today, but hope to give it a shot tonight.  Nevertheless, I thought I would share what I'd found so far.

**Comment by chregu** [comment]
The latest packages from php-osx.liip.ch support TLS 1.2 in curl and the test script above should return the right thing. That problem is solved. The problem @fullybaked has is that `fopen` doesn't support TLS 1.2, neither in Apples PHP
```
 /usr/bin/php -i  | grep "Registered Stream Socket Transports "
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls
```

nor in ours
````
$ /usr/local/php5/bin/php -i  | grep "Registered Stream Socket Transports "
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0
````
I can try to compile the latest openssl. That alone is not too hard, I'm more "scared" of dependencies in apache or other apache modules which maybe use the built in openssl library.

Will have a look, but can't promise when

**Comment by lphilps** [comment]
Ooops. Thanks for straightening me out. I just updated to the latest version and curl is now able to make tls 1.2 connections with modern cipher suites.  Perfect.  Many thanks!

**Comment by mjmartin** [comment]
Same with SoapClient too.

**Comment by rgazelot** [comment]
Since the latest update of [OSX ElCaptain 10.11.4](https://support.apple.com/fr-fr/HT205750) I have an issue with cURL on httpS urls.

`SSL certificate problem: unable to get local issuer certificate`

I had to reinstall using `curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6`. It works, but I don't know exactly why. If someone have the answer, I would like to know why?

More informations: In my `php -i | grep SSL Version` I was using `OpenSSL/2.0.0` and now it's using `SecureTransport`.

**Comment by billytd** [comment]
I too have been using liip's php-osx install for years and it has been great!

I was also having this issue and I'm running OS X 10.11.4, though I'm not exactly sure which version of OS X the problem began occurring for me.

My solution was to use homebrew to install php following [these directions](http://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error). (I used php70 instead of php55.)

**Comment by chregu** [comment]
i'm right now working on making openssl 1.0.2 included in the package

**Comment by chregu** [comment]
Looking good. I updated now the php 7.0.8 build with openssl 1.0.2h. can you please try if that works for you?

**Comment by chregu** [comment]
All latest builds (see below) are now compiled against opensssl 1.0.2h and it seems to run fine for me, so I'll close this issue. If you still have problems, please reopen

```
PHP 7.0.8 for OS X 10.10/10.11 uploaded at 2016-06-26

PHP 5.6.23 for OS X 10.10/10.11 uploaded at 2016-06-26
PHP 5.6.23 for OS X 10.8/10.9   uploaded at 2016-06-26

PHP 5.5.37 for OS X 10.10/10.11 uploaded at 2016-06-26
PHP 5.5.37 for OS X 10.8/10.9   uploaded at 2016-06-26
```

**Comment by GDmac** [comment]
just installed 7.0.8 and using curl throws
```php
CURLOPT_SSL_VERIFYPEER => true`` 
// curl error (51) : SSL: certificate verification failed (result: 5)

CURLOPT_SSL_VERIFYPEER => false
// curl error (35) : SSL: CA certificate set, but certificate verification is disabled

**Comment by chregu** [comment]
please provide a complete self-running example, it's hard to debug this way

**Comment by chregu** [comment]
I see the problem.. `CURLOPT_SSL_VERIFYPEER => false` doesn't really work with Apple's SecureTransport (I didn't find an easy solution or workaround). As we have now openssl 1.0.2, I can try to link curl against that. Just not today

Furthermore your SSL certificate on the server is not a validly signed one, that's why `CURLOPT_SSL_VERIFYPEER => true` doesn't work you either. But that wouldn't work on any system, not just this.

**Comment by GDmac** [comment]
seems to be a google thing as github works here
```php
$ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, "https://github.com");
curl_setopt($ch, CURLOPT_URL, "https://google.com");

curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$result = curl_exec($ch);
if ($n = curl_errno($ch)) { 
	throw new \Exception("curl error ($n) : ".curl_error($ch));
}
var_dump($result);
curl_close($ch);
```

**Comment by GDmac** [comment]
for now i have reverted to 7.0.4...
is this the correct method?
``sudo ln -s /usr/local/php5-7.0.4-20160310-143636 /usr/local/php5``

**Comment by chregu** [comment]
`sudo ln -s /usr/local/php5-7.0.4-20160310-143636 /usr/local/php5` is the correct method (plus `sudo apachectl restart`)

**Comment by GDmac** [comment]
Looks like 7.0.4 also uses Apple SecureTransport.
the difference being, under phpinfo() openSSL it has no cafile set. 
When i remove (comment out that line) then 7.0.8 also seems to work fine.
```
\\file: php.d/40-openssl.ini
# openssl.cafile=/usr/local/php5/ssl/certs/cacert.pem``
```
```
openssl
Directive         Local Value   Master Value
openssl.cafile    no value      no value
openssl.capath    no value      no value
```

**Comment by GDmac** [comment]
Just installed ``php5-7.0.12-20161101-102255`` and this is still an issue.
i had to disable openssl cafile for some sites to work
```
\\ file: /usr/local/php5-7.0.12-20161101-102255/php.d/40-openssl.ini
# openssl.cafile=/usr/local/php5/ssl/certs/cacert.pem
```

**Comment by peterrehm** [comment]
Disabling the cafile works for me as well.

**Comment by rogeriotaques** [comment]
Same issue with wither 5.6 and 7.1.0!
Disabling the cafile works for me as well.

**Comment by IvoPereira** [comment]
Same issue here too with 7.1.0.

Solved too disabling cafile on **/usr/local/php5-7.1.1-20170213-100732/php.d/40-openssl.ini**

**Comment by chregu** [comment]
I recompiled now all versions on 10.10+ with openssl enabled and not using Apple's SecureTransfer anymore. I hope this solves some problems
