### ISSUE TITLE
Error on PHP 5.6 installation

### ISSUE THREAD

**Issue by xti21** [liip/php-osx#231]
Hi everyone,

I'm trying to install PHP 5.6 on my Mac OS Sierra using terminal.
When I try to install following your homepage instructions, terminal shows me an error:

```
iMac-de-Xavi:~ xavi$ curl -s https://php-osx.liip.ch/install.ch | bash -s 5.6
bash: line 1: !DOCTYPE: No such file or directory
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
```

Has anyone see it before?

Thank you so much in advance

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
