### ISSUE TITLE
After installing php7.1 - it works very slow

### ISSUE THREAD

**Issue by reggin** [liip/php-osx#234]
/usr/local/php5/bin/php -v - very slow operation. Do you know, how to fix it?

**Comment by sewerside** [comment]
i experienced this too... no solution for this? I removed the /usr/bin/php5 then try to install again and now it take extremely long time to install and can't be completed

**Comment by chregu** [comment]
It's a known issue, see this https://github.com/liip/php-osx/issues/102#issuecomment-74635779

**Comment by sewerside** [comment]
Thanks @chregu for your reference. I have managed to solve it now. What I did was commented the imap extension. 

vi /usr/local/php5/php.d/50-extension-imap.ini
;extension=imap.so

---

time php -v
PHP 7.2.0RC2 (cli) (built: Oct  2 2017 08:48:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0RC2, Copyright (c) 1999-2017, by Zend Technologies

real	0m0.094s
user	0m0.051s
sys	0m0.023s

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
