### ISSUE TITLE
PHP 7.1 not rendering PHP

### ISSUE THREAD

**Issue by savante21** [liip/php-osx#236]
I'm having a harder time with this than I think I should.  

After doing the 1 step installation, the /etc/apache/httpd.conf did not have the old php module commented out.  This caused a server error when trying to open "phpinfo.php" page.

After commenting the old php module out, my php page does not render.  
When viewing source, the php code is visible.  

when I type 'which php' i see :
/usr/local/php5/bin/php

when I type 'php -V' I see:
PHP 7.1.9 (cli) (built: Sep 14 2017 10:05:35) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

I see that at the bottom of the /etc/apache/httpd.conf file the following exists:
Include /private/etc/apache2/other/*.conf

I verified that this is just a link and that +php-osx.conf exists in /private/etc/apache2/other/ as well as /etc/apache2/other/.

Cannot determine why php pages arent rendered.

**Comment by mjsarfatti** [comment]
Same here... Seems like there is one installation step missing: how to configure Apache.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
