### ISSUE TITLE
Can't install: "Your version of OS X is not supported, you need at least 10.6"

### ISSUE THREAD

**Issue by jplew** [liip/php-osx#237]
Hi: 
I'm running Mac OS X Sierra 10.12.6, and I get this error message when attempting to install any version of PHP via the command line:

`
****
Your version of OS X ((standard input):1:10.12) is not supported, you need at least 10.6
Stopping installation...
If you think that's wrong, try
****
curl -o install.sh -s https://php-osx.liip.ch/install.sh | bash install.sh force
****
`

I think there's a problem with the comparison operation. The second method fails as well:
`install.sh: No such file or directory`

**Comment by pixelwhip** [comment]
I'm experiencing the same issue. I'm on OS X 10.13.1

**Comment by pixelwhip** [comment]
I think my issue is due to a default `-n` flag I have set for grep which outputs the line number in the result. Therefor the command

```
OS_VERSION=`sw_vers -productVersion | egrep --color=never -o '10\.[0-9]+'`
```

returns `1:10.13` instead of `10.13` which is not recognized as a valid version.

I was able to workaround it by downloading the script and changing that line to use `ag`

```
OS_VERSION=`sw_vers -productVersion | ag --nocolor -o '10\.[0-9]+'`
```

**Comment by epicanriome** [comment]
I encountered the same problem, I am on OSX 10.10 and I couldn't upgrade PHP, I resolved it thanks to @pixelwhip. I didn't have the same command line to get the OS_VERSION.
I had

`sw_vers -productVersion | egrep --color=never -o '10\.[0-9]+\.[0-9]+'` 

so it was expecting something like `10.XX.XX` but my version was giving to egrep something like `10.XX`
So I just removed the last part of the regexp, it gave me something like this

`sw_vers -productVersion | egrep --color=never -o '10\.[0-9]+'`

**Comment by duannx** [comment]
I don't know why need to check the OS version but the problem will persist if you have macOS version >= 10.15. I just add my version to the if-else to make it work.
Relace this line:
`if [[ $OS_VERSION == "10.14" ]]; then`
with this line
```
if [[ $OS_VERSION == "10.15" ]]; then
        echo "Now you fucked up"
    elif [[ $OS_VERSION == "10.14" ]]; then
```

**Comment by lardnicus** [comment]
This issue is still happening in 10.15

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
