### ISSUE TITLE
Does not work in El Capitan system using Server.app

### ISSUE THREAD

**Issue by RobLewis** [liip/php-osx#245]
As I feared, it's not working. LoadModule for php5 is commented out in httpd.conf, and yet it still uses my old default install of PHP 5.5. 
There's a link: /usr/local/php5 -> /usr/local/php5-7.2.2-20180201-132629 
I renamed the old /private/etc/apache2/other/php5.conf, adding '.old' to the file name. 
Another link: /private/etc/apache2/other/+php-osx.conf -> /usr/local/php5-7.2.2-20180201-132629. 
I note that the Websites control panel in Server.app has a checkbox to "enable PHP", which I have tried unchecking and rechecking.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
