### ISSUE TITLE
pdo_dblib not bundled in 7.0.27

### ISSUE THREAD

**Issue by bluec** [liip/php-osx#248]
As per title. Any reason for this? I had to build it from source and it worked fine, so just wondering why it is left out?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
