### ISSUE TITLE
Did or could not download package: 5.6-10.10-frontenddev

### ISSUE THREAD

**Issue by cweric** [liip/php-osx#252]
$  curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6
****
[WARNING]
Detected macOS High Sierra 10.13. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/5.6-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/5.6-10.10/frontenddev/5.6-10.10-frontenddev-5.6.36-20180623-103305.tar.bz2

downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6-10.10-frontenddev.tar.bz2
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6-10.10-frontenddev.tar.gz
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/5.6-10.10-frontenddev.tgz
Did or could not download package: 5.6-10.10-frontenddev
Finished.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
