### ISSUE TITLE
How can i do install specific version?

### ISSUE THREAD

**Issue by mahirfatihunal** [liip/php-osx#253]
Hi all,

How can i do install specific version?
For example php5-7.2.2-20180201-132629

`curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2.2-20180201-132629  `

or

`curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2.2`

i have tried it but it doesnt possible.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
