### ISSUE TITLE
PHP: 5.3.29 , wrong php-fpm version in package

### ISSUE THREAD

**Issue by danielemaggio** [liip/php-osx#256]
Hi there,

I needed to install php 5.3.29 to debug and mantain an old symfony 2.3 app;
since I use a XAMPP stack on mac i used to configure vHost with FPM , launching fpm version i need;

using 5.3.29 by you package is great and i avoided to compile from source but there is a problem cause it has a wrong php-fpm version;

here what i get for php:
>balrog:~ daniele$ /usr/local/php5-5.3.29-20141019-211753/bin/php -v
PHP 5.3.29 (cli) (built: Oct 19 2014 21:11:22) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

here what i get for php-fpm:
>balrog:~ daniele$ /usr/local/php5-5.3.29-20141019-211753/sbin/php-fpm -v
PHP 5.4.34 (fpm-fcgi) (built: Oct 19 2014 21:00:26)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
