### ISSUE TITLE
After installing PHP 5.6.36 phpmyadmin little bit broken :)

### ISSUE THREAD

**Issue by shaymuratov** [liip/php-osx#257]
After update PHP 5.5 on os x 10.11 to 5.6 liip phpmyadmin SQL Form not working, just printed "Loading" and finished without error and result
Export/Import also does not work
But CRUD with user interface working fine
When i back 5.5 php all work fine again
Please help me

Web server
Apache/2.4.28 (Unix) PHP/5.6.36
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.36

**Comment by dmitriydzyuba** [comment]
had the same, looks like something is wrong with binary or modules. 

it's not only phpmyadmin, some of my scripts wasn't working as well. Loading CPU at 100% until met max execution time. Had to go back to brew version.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
