### ISSUE TITLE
macosx upgrade php 7.1 to 7.2 dont work in phpinfo()

### ISSUE THREAD

**Issue by rafaelgilead** [liip/php-osx#258]
I followed the tutorial but the php version does not update in apache. what to do ?

Commented the line:
#LoadModule php7_module libexec/apache2/libphp7.so
And load on file +php-osx.conf
LoadModule php7_module /usr/local/php5/libphp7.so
and.. PHP don't execute.

**Comment by phena109** [comment]
Which version of mac are you on? Majave have serious issue with (ref: #249)

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
