### ISSUE TITLE
Special handling for macOS Server?

### ISSUE THREAD

**Issue by RobLewis** [liip/php-osx#260]
I have very long (but not very deep) experience with OS X Server (AKA macOS Server), and it has always been a bit of a strange beast. Things that work on regular macOS don't work with Server. Files live in different places, etc. 

Has anyone undertaken to produce a version of `php-osx` that works with Server? Evidently Apple keeps paring back the feature list in successive versions of Server, so maybe it's converging on regular macOS. I'd like to be sure.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
