### ISSUE TITLE
original apache not loading foreign libraries anymore.

### ISSUE THREAD

**Issue by hanifeoglu** [liip/php-osx#263]
Hi want to update 7.1 to 7.2 or 7.3 but i m get it  to this 
[WARNING]
Detected macOS Mojave 10.14. There are serious issues with it, due to the original apache not loading
foreign libraries anymore. PHP within apache will most certainly not work anymore if you proceed!
The cli version still will.
See this issue at https://github.com/liip/php-osx/issues/249 for details and discussion
Restart this script with
 curl -s https://php-osx.liip.ch/install.sh | bash -s force 7.3
to really install it
now my system PHP Version 7.1.19 is working  how to fix it

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
