### ISSUE TITLE
Installation does not update the php version on  MacOs High Sierra 

### ISSUE THREAD

**Issue by onlyjazz** [liip/php-osx#264]
Did the standard online install for 7.2.  Restarted apachectl
System continues to run php 7.1 and does not load the php-osx extensions

```

**Comment by onlyjazz** [comment]
OK - I'm seeing that this is a recurring theme - same problem as #258 
You cannot comment out the original php7.so in the http2.conf and you cannot replace the shared library due to /usr/bin SIP - maybe this is the root cause.

**Comment by onlyjazz** [comment]
More data - if you rename the default php.ini in /etc you get a WSOD

So back to my original objective - enable intl.so

I installed the php for os/x repo.

Created a 1 line php.ini

`extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/intl.so
`

Could have compiled the extension from the 7.1 source but this was at the end of the day a faster and easier solution

Still wondering if there is a solution to use php for os/x on High Sierra

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
