### ISSUE TITLE
php 7.3.0beta3 no zip extension

### ISSUE THREAD

**Issue by masdatli** [liip/php-osx#265]
On php 7.3 I couldnt install facebook/webdriver because de zip extension was not installed. 
On php 7.2 it does work. Maybe this will save someone a couple of work trying to install pecl-zip & ziplib.

**Comment by JeanStRd** [comment]
On PHP 7.3.3 (PHP 7.3.3 for OS X 10.10-10.13 uploaded at 2019-03-30) the zip extension is again missing !

**Comment by jennrei** [comment]
I have the same problem. Is there any solution?

**Comment by guntursp** [comment]
Same with @JeanStRd, PHP 7.3.3 (PHP 7.3.3 for OS X 10.10-10.13 uploaded at 2019-03-30) still missing zip extension.

**Comment by guntursp** [comment]
Hello @masdatli @JeanStRd @jennrei,

Today, I've experienced the same issue with PHP-OSX 7.3.3, **it is missing zip extension.**
After I did some digging on Google, this is my workaround: _(please make sure we have any permissions required for these processes)_
1. Zip Extension, it is actually requires **'libzip'** to be working. If our system already have 'libzip' installed then we actually able to install zip extension with this command
`pecl install zip`

2. But if our system **don't have libzip** yet, the journey is begin from here. We can download libzip from here: https://libzip.org/download/. I tried with:
`cd /usr/local/src`
`curl --remote-name https://libzip.org/download/libzip-1.5.2.tar.gz`
`tar -xzvf libzip-1.5.2.tar.gz`

3. For installing 'libzip', it requires **CMake** and can be downloaded from here:
https://cmake.org/download/. I tried with:
`download the installer package for MacOS, the link should be something like this (https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Darwin-x86_64.dmg)`
`install it as usual`

4. After installation success, make sure that 'cmake' can also be accessed in command line, to call cmake, can be set up with:
`nano ~/.bash_profile`
`export PATH=/Applications/CMake.app/Contents/bin:$PATH`
`source ~/.bash_profile`

5. Build and install libzip
     a. Open CMake app, from launcher.
     b. Browse Source, point it to `/usr/local/src/libzip-1.5.2` (or any place that we've extracted the source from point no.2 above).
     c. Browse Build, in my case I set this up to `/Users/<username>/Library/Zip` (or any place that we have the permission with)
     d. Click Configure button, if ok it will says `Configuring done`
     e. Click Generate button, if ok it will says `Generating done`
     f. Open Terminal, then `cd /Users/<username>/Library/Zip`  (or any place that we have choose for 'Browse Build' from point c)
then execute `make`
following `make install`
it will shows something like this in the terminal
`Install the project...`
`-- Install configuration: ""`
`-- Installing: /usr/local/lib/pkgconfig/libzip.pc`
`-- Installing: /usr/local/include/zipconf.h`
`-- Installing: /usr/local/include/zip.h`
`....... etc`

6. Hooraaayy! We finally have libzip installed on our machine. Now, it's the time for install the **Zip** extension it self. Remember on the point no.1, because we already have libzip installed now we're able to execute this command line
`pecl install zip`
After successful installation, it will shows something like this:
`Build process completed successfully`
`Installing '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20180731/zip.so'`
`install ok: channel://pecl.php.net/zip-1.15.4`
`configuration option "php_ini" is not set to php.ini location`
`You should add "extension=zip.so" to php.ini`

7. Add that into our php.ini, to verified the module is installed, we can check with
`php -m` make sure `zip` module is there.

8. Restart the PHP-FPM and the WebServer (Nginx or Apache).

9. Try to access our info.php, it should shows something like this 
![image](https://user-images.githubusercontent.com/2078953/57425955-9932d280-7247-11e9-82c5-23de710fb3e3.png)

Hopefully this will help until PHP-OSX next release...
Cheers!

**Comment by jennrei** [comment]
Thanks @guntursp! Your workaround solved it :)

**Comment by namrehcram** [comment]
@guntursp you're the man!

**Comment by othyn** [comment]
Thanks @guntursp!

Just a heads up to anyone else, I'm on macOS 10.14.3 (18D109), its even easier if you have brew installed:

1. First run `$ brew install autoconf libzip` to install the base components
2. Then run `$ pecl install zip` to install the extension
3. Then run `$ php --ini` to find the ini and open it in your editor of choice, e.g. `$ subl /usr/local/php5/lib/php.ini`
4. Add `extension=zip.so` as an enabled extension under the extensions area of the file (find `Dynamic Extensions` - doesn't have to be there, but keeps things organised)
5. Save & done!

**Comment by chregu** [comment]
The zip extension is back with the latest release (7.3.6)
