### ISSUE TITLE
Missing Libsodium extension

### ISSUE THREAD

**Issue by KirbyFox** [liip/php-osx#266]
Please include the Libsodium extension within your PHP 7.3.x distro.

**Comment by GDmac** [comment]
+100 libsodium is included with >= php 7.2 please include it with=

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.

**Comment by GDmac** [comment]
Thank you for years of supplying an awesome build.
