### ISSUE TITLE
Enable WebP support in GD

### ISSUE THREAD

**Issue by pethr** [liip/php-osx#269]
Hi, would you consider enabling WebP support in GD? Thank you.

**Comment by Trurl101** [comment]
I agree, webp support seems to be standard in most online php manuals (most don't even mention anymore that it is new). Its disappointing that this php version not supports it.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
