### ISSUE TITLE
apache configuration file on macOS Mojave

### ISSUE THREAD

**Issue by bossofrap** [liip/php-osx#270]
when I write :wp after doing anything to the httpd.config file I get the following message: E163 there is only one file to edit. what can i do about this, I cant activate php due to this.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
