### ISSUE TITLE
PHP 7.1, 7.2, 7.3 High Sierra: SSI Injection bug

### ISSUE THREAD

**Issue by Ivan219** [liip/php-osx#272]
Good afternoon, there was a problem when pasting through the SSI when processing long texts:
There are two files: menu.html and index.html
Content index.html:
```
<! - # include virtual = "/ menu.html" -> [And 7962 Latin characters]
```
menu.html is inserted after these 7962 characters, although it should have been earlier. If the signs are 7961 or less, then everything is fine. What could be the problem?

If the example is made more complex, then a few more lines will appear: menu.html is downloaded two times, html tags fly off and new ones are added.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
