### ISSUE TITLE
Cannot install and use 5.6 and 7.x at the same time.

### ISSUE THREAD

**Issue by timbkbasic** [liip/php-osx#274]
On my machine, I have the requirement that I run PHP 5.6 and PHP 7.x together. PHP 5.6 is used by MAMP to support a legacy website, and PHP 7.x is required for new Laravel development.

However, because both PHP5 and PHP7 point to the same directory:
   /usr/local/bin/php5
for their configurations, the two cannot be used simultaneously.

This seems like an unnecessary configuration.

I do not understand why PHP5.6 cannot point to:
   /usr/local/bin/php5

and PHP7.x point to:
   /usr/local/bin/php7

If this simple change was made, we would be able to run the two versions together.

Is it possible to make PHP7.x point to /usr/local/php7?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
