### ISSUE TITLE
php 7.4 

### ISSUE THREAD

**Issue by samsonasik** [liip/php-osx#276]
Hi, any chance for php 7.4 installer? thank you

**Comment by chregu** [comment]
Not really. Or not any time soon. We recommend using homebrew, if you want the latest and greatest PHP. https://getgrav.org/blog/macos-catalina-apache-multiple-php-versions has a pretty thorough walk through for setting that up

**Comment by davidromani** [comment]
@chregu thank you, but if you have an old macOS version (like 10.10) it doesn't works :-(

**Comment by LittleCoding** [comment]
About time to revisit this just yet? 7.3 is moving to Security Fixes Only at the start of next year.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
