### ISSUE TITLE
Problem with install PHP in macOs 10.14

### ISSUE THREAD

**Issue by ArtemHarbetskyi** [liip/php-osx#277]
Your version of OS X () is not supported, you need at least 10.6
Stopping installation...
If you think that's wrong, try

`curl -o install.sh -s https://php-osx.liip.ch/install.sh | bash install.sh force`

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
