### ISSUE TITLE
ldap missing in 7.3 

### ISSUE THREAD

**Issue by timwolf** [liip/php-osx#278]
php -m shows ldap in 7.1 and 7.2 builds
That appears not to be the case in 7.3+  

I have standard symfony libraries that require it that are no longer working for me.  Can you please include ldap in the build?

**Comment by JohnEeeDee** [comment]
Seeing the same thing; ldap is supposed to be included according to the docs, but it's missing in 7.3.x

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
