### ISSUE TITLE
Memcached is missing for PHP 7.3

### ISSUE THREAD

**Issue by filitchp** [liip/php-osx#279]
After installing PHP 7.3 you can run `php -m | grep memcached` to verify memcached did not load. The .so is not present either (`ls /usr/local/php5/lib/php/extensions/no-debug-non-zts-20180731/ | grep memcached`).

This workaround did the trick for me:
```bash
sudo /usr/local/php5/bin/pecl install memcached

# ...
# Build process completed successfully
# Installing '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20180731/memcached.so'
# install ok: channel://pecl.php.net/memcached-3.1.5
# configuration option "php_ini" is not set to php.ini location
# You should add "extension=memcached.so" to php.ini

echo 'extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20180731/memcached.so' | sudo tee /usr/local/php5/php.d/50-extension-memcached.ini
```

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
