### ISSUE TITLE
PHP 5.4.16 ( Centos 7 Version ) 

### ISSUE THREAD

**Issue by jqr91** [liip/php-osx#282]
Is it possible to compile php 5.4.16 with extension for MAMP ( Osx ) ?

Thanks!

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
