### ISSUE TITLE
Extension request: imagick

### ISSUE THREAD

**Issue by ojtibi** [liip/php-osx#62]
I am suggesting the imagick extension to be included in the next release. I came across problems when I was installing ImageMagick via MacPorts, and then attempting to install imagick via pecl.

This issue will serve as a discussion thread on how it is (or not) feasible to include imagick in the next release.

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
