### ISSUE TITLE
how to add support for interbase/firebird

### ISSUE THREAD

**Issue by BasilSnowman** [liip/php-osx#65]
I apologize for autotranslation. how to add support for interbase / firebird in the php-osx? thank you in advance for your attention.

**Comment by zkrat** [comment]
Hi ,
I also need support for interbase. Any suggestion?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
