### ISSUE TITLE
Oracle oci8 extension

### ISSUE THREAD

**Issue by iJakeSays** [liip/php-osx#9]
Any plans to add or help with adding the oci8 extension for use with the instantclient? Been struggling with this for a good while now and really need to get it working. I've tried everything I know to get it added to the stock php but just can't get it to work. If it were part of you installer my life would be complete.

**Comment by npotier** [comment]
Hello @keriati this issue is very old, but would you mind to share your solutions ?

Thank you !

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
